#!/bin/bash
(cd /media/sf_GA/GeneticSolver/panda-temp//temp-archive-dir-8d99-63ac-e8dc-6e28; ar x /home/ubuntu/panda/lib/panda/libbambu_gcc7.a)  > /media/sf_GA/GeneticSolver/panda-temp/shell_output_0 2>&1 
