#!/bin/bash
(cd /media/sf_GA/GeneticSolver/panda-temp//temp-archive-dir-303d-882f-18aa-7274; ar x /home/ubuntu/panda/lib/panda/libsoftfloat_gcc7.a)  > /media/sf_GA/GeneticSolver/panda-temp/shell_output_6 2>&1 
